name: flutter_earth_history
description: Flutter Earth History UI Challenge App

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  go_router: ^10.0.0
  hooks_riverpod: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
